/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\swaetshirt_men_gltf_orange.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function SweatShirtModel(props) {
  const { nodes, materials } = useGLTF('/swaetshirt_men_gltf_orange.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.144, 1.233, 0.093]} rotation={[0.085, -0.99, 0.169]}>
        <mesh geometry={nodes.ZipperSlider3751887_Node.geometry} material={materials.Material4193315} />
        <mesh geometry={nodes.ZipperPuller4193308_Node.geometry} material={materials.Material4193313} position={[0, 0, 0.003]} />
      </group>
      <group position={[-0.073, 1.2, 0.125]} rotation={[-0.166, -0.395, -0.289]}>
        <mesh geometry={nodes.ZipperSlider4152894_Node.geometry} material={materials.Material4192685} />
        <mesh geometry={nodes.ZipperPuller4192678_Node.geometry} material={materials.Material4192683} position={[0, 0, 0.003]} />
      </group>
      <group position={[0.28, 1.446, 0.017]} rotation={[0.636, -0.667, 1.133]}>
        <mesh geometry={nodes.ZipperSlider4487971_Node.geometry} material={materials.Material4487977} />
        <mesh geometry={nodes.ZipperPuller4487992_Node.geometry} material={materials.Material4488143} position={[0, 0, 0.003]} />
      </group>
      <group position={[-0.19, 1.221, -0.078]} rotation={[2.953, -0.573, 2.557]}>
        <mesh geometry={nodes.ZipperSlider4686650_Node.geometry} material={materials.Material4747690} />
        <mesh geometry={nodes.ZipperPuller4747683_Node.geometry} material={materials.Material4747688} position={[0, 0, 0.003]} />
      </group>
      <mesh geometry={nodes.MatShape_274666_Node.geometry} material={materials.PT_FABRIC_FRONT_32094} />
      <mesh geometry={nodes.MatShape_275632_Node.geometry} material={materials.PT_FABRIC_FRONT_32094} />
      <mesh geometry={nodes.MatShape_276018_Node.geometry} material={materials.PT_FABRIC_FRONT_46120} />
      <mesh geometry={nodes.MatShape_276074_Node.geometry} material={materials.PT_FABRIC_FRONT_46183} />
      <mesh geometry={nodes.MatShape_276266_Node.geometry} material={materials.PT_FABRIC_FRONT_46204} />
      <mesh geometry={nodes.MatShape_276322_Node.geometry} material={materials.PT_FABRIC_FRONT_46225} />
      <mesh geometry={nodes.MatShape_281708_Node.geometry} material={materials.PT_FABRIC_FRONT_46275} />
      <mesh geometry={nodes.MatShape_281716_Node.geometry} material={materials.PT_FABRIC_FRONT_46299} />
      <mesh geometry={nodes.MatShape_284077_Node.geometry} material={materials.PT_FABRIC_FRONT_46423} />
      <mesh geometry={nodes.MatShape_284085_Node.geometry} material={materials.PT_FABRIC_FRONT_46445} />
      <mesh geometry={nodes.MatShape_284866_Node.geometry} material={materials.PT_FABRIC_FRONT_46569} />
      <mesh geometry={nodes.MatShape_284874_Node.geometry} material={materials.PT_FABRIC_FRONT_46591} />
      <mesh geometry={nodes.MatShape_287136_Node.geometry} material={materials.PT_FABRIC_FRONT_46716} />
      <mesh geometry={nodes.MatShape_287144_Node.geometry} material={materials.PT_FABRIC_FRONT_46740} />
      <mesh geometry={nodes.ZipperStopper3751933_Node.geometry} material={materials.Material4193317} position={[-0.145, 1.241, 0.093]} rotation={[0.085, -0.99, 0.169]} />
      <mesh geometry={nodes.ZipperStopper3751945_Node.geometry} material={materials.Material4193317} position={[-0.145, 1.241, 0.093]} rotation={[-3.102, 0.802, 2.986]} />
      <mesh geometry={nodes.ZipperStopper3751966_Node.geometry} material={materials.Material4193319} position={[-0.134, 1.06, 0.097]} rotation={[0.025, -0.805, 0.114]} />
      <mesh geometry={nodes.ZipperStopper3751979_Node.geometry} material={materials.Material4193319} position={[-0.134, 1.06, 0.097]} rotation={[3.131, 0.357, 3.084]} />
      <mesh geometry={nodes.ZipperStopper4152940_Node.geometry} material={materials.Material4192687} position={[-0.07, 1.208, 0.124]} rotation={[-0.166, -0.395, -0.289]} />
      <mesh geometry={nodes.ZipperStopper4152952_Node.geometry} material={materials.Material4192687} position={[-0.07, 1.208, 0.124]} rotation={[2.97, 0.41, -2.851]} />
      <mesh geometry={nodes.ZipperStopper4152973_Node.geometry} material={materials.Material4192689} position={[-0.109, 1.065, 0.115]} rotation={[-0.077, -0.459, -0.334]} />
      <mesh geometry={nodes.ZipperStopper4152986_Node.geometry} material={materials.Material4192689} position={[-0.109, 1.065, 0.115]} rotation={[3.088, 0.396, -2.824]} />
      <mesh geometry={nodes.ZipperStopper4488017_Node.geometry} material={materials.Material4488145} position={[0.274, 1.451, 0.015]} rotation={[0.636, -0.667, 1.133]} />
      <mesh geometry={nodes.ZipperStopper4488029_Node.geometry} material={materials.Material4488145} position={[0.274, 1.451, 0.015]} rotation={[-0.523, 0.227, 0.819]} />
      <mesh geometry={nodes.ZipperStopper4488050_Node.geometry} material={materials.Material4488147} position={[0.361, 1.334, 0.02]} rotation={[0.602, -0.352, 0.404]} />
      <mesh geometry={nodes.ZipperStopper4488063_Node.geometry} material={materials.Material4488147} position={[0.361, 1.334, 0.02]} rotation={[-2.062, 0.97, 2.498]} />
      <mesh geometry={nodes.ZipperStopper4686696_Node.geometry} material={materials.Material4747692} position={[-0.193, 1.229, -0.078]} rotation={[2.953, -0.573, 2.557]} />
      <mesh geometry={nodes.ZipperStopper4686708_Node.geometry} material={materials.Material4747692} position={[-0.193, 1.229, -0.078]} rotation={[2.963, -0.556, 2.843]} />
      <mesh geometry={nodes.ZipperStopper4686729_Node.geometry} material={materials.Material4747694} position={[-0.136, 1.053, -0.108]} rotation={[2.898, -1.153, 2.598]} />
      <mesh geometry={nodes.ZipperStopper4686742_Node.geometry} material={materials.Material4747694} position={[-0.136, 1.053, -0.108]} rotation={[2.889, -1.159, 2.565]} />
      <mesh geometry={nodes.StitchMatShape_271999_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_272103_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_272206_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_272317_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_272421_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_272436_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_272587_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_272691_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_272794_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_272905_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_273009_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_273024_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_273196_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_273363_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_273530_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_273697_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_273869_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_274036_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_274203_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_274370_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_274514_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_274658_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_274770_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_274943_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_275029_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_275108_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_275182_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_275324_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_275466_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_275545_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_275624_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_275736_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_275909_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_275995_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_276066_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_276094_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_276114_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_276162_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_276210_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_276258_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_276314_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_276342_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_276362_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_276410_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_276458_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_276506_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_276857_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_277188_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_277292_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_277394_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_277496_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_277600_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_277659_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_277718_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_278054_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_278385_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_278716_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_279047_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_279378_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_279709_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_280040_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_280371_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_280702_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_281033_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_281364_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_281532_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_281700_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_281844_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_281869_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_281896_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_281997_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282021_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282144_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282173_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282199_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282223_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282257_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282281_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282315_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282389_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282458_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282577_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282759_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282782_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282805_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282924_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_282977_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_283030_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_283059_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283252_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283446_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283470_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283499_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283525_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283549_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283583_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283607_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283641_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283769_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283794_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283821_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283922_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_283946_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284069_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284205_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284275_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284294_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284397_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284416_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284486_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284528_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_284648_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284668_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284687_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284790_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284809_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284829_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_284858_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_285210_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_285541_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_285872_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_285984_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_286089_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_286194_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_286306_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_286481_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_286641_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_286704_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_286793_Node.geometry} material={materials.Material32785} />
      <mesh geometry={nodes.StitchMatShape_286968_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.StitchMatShape_287128_Node.geometry} material={materials.Material32604} />
      <mesh geometry={nodes.Sleeves.geometry} material={materials.Sleeves_FRONT_32308} />
      <mesh geometry={nodes.Sleeves_1.geometry} material={materials.Sleeves_FRONT_32308} />
      <mesh geometry={nodes.Sleeves_2.geometry} material={materials.Sleeves_FRONT_32308} />
      <mesh geometry={nodes.Sleeves_3.geometry} material={materials.Sleeves_FRONT_32308} />
      <mesh geometry={nodes.Sleeves_4.geometry} material={materials.Sleeves_FRONT_32308} />
      <mesh geometry={nodes.Sleeves_5.geometry} material={materials.Sleeves_FRONT_32308} />
      <mesh geometry={nodes.Pattern_814930.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_814930_1.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_814930_2.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_814931.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_814931_1.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_814931_2.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_897947.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_897947_1.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_897947_2.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_897948.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_897948_1.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_897948_2.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Internal_Line_1076031.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.Internal_Line_1076031_1.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.Internal_Line_1076031_2.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.Internal_Line_1156680.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.Internal_Line_1156680_1.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.Internal_Line_1156680_2.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.Internal_Line_1076032.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.Internal_Line_1076032_1.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.Internal_Line_1076032_2.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.BindingPattern_2327953.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.BindingPattern_2327953_1.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.BindingPattern_2327953_2.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.BindingPattern_2328040.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.BindingPattern_2328040_1.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.BindingPattern_2328040_2.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.BindingPattern_2334657.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.BindingPattern_2334657_1.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.BindingPattern_2334657_2.geometry} material={materials.Body_FRONT_32290} />
      <mesh geometry={nodes.Pattern_3071643.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071643_1.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071643_2.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071644.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071644_1.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071644_2.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071645.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071645_1.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071645_2.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071646.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071646_1.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Pattern_3071646_2.geometry} material={materials.rib2X2_FRONT_32317} />
      <mesh geometry={nodes.Internal_Line_1076033.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_1076033_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_1076033_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_1156681.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_1156681_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_1156681_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_1076034.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_1076034_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_1076034_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Body_Front_1.geometry} material={materials.Body_FRONT_32299} />
      <mesh geometry={nodes.Body_Front_1_1.geometry} material={materials.Body_FRONT_32299} />
      <mesh geometry={nodes.Body_Front_1_2.geometry} material={materials.Body_FRONT_32299} />
      <mesh geometry={nodes.Body_Front_2.geometry} material={materials.Body_FRONT_32299} />
      <mesh geometry={nodes.Body_Front_2_1.geometry} material={materials.Body_FRONT_32299} />
      <mesh geometry={nodes.Body_Front_2_2.geometry} material={materials.Body_FRONT_32299} />
      <mesh geometry={nodes.ZipperPattern_3751845.geometry} material={materials.Fabric3752026_FRONT_46253} />
      <mesh geometry={nodes.ZipperPattern_3751845_1.geometry} material={materials.Fabric3752026_FRONT_46253} />
      <mesh geometry={nodes.ZipperPattern_3751845_2.geometry} material={materials.Fabric3752026_SIDE_46253} />
      <mesh geometry={nodes.ZipperPattern_3751858.geometry} material={materials.Fabric3752026_FRONT_46253} />
      <mesh geometry={nodes.ZipperPattern_3751858_1.geometry} material={materials.Fabric3752026_FRONT_46253} />
      <mesh geometry={nodes.ZipperPattern_3751858_2.geometry} material={materials.Fabric3752026_SIDE_46253} />
      <mesh geometry={nodes.Internal_Line_3855446.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855446_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855446_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855448.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855448_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855448_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855452.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855452_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855452_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855453.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855453_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855453_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855449.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855449_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855449_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855447.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855447_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_3855447_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.ZipperPattern_4152852.geometry} material={materials.Fabric4153031_FRONT_46401} />
      <mesh geometry={nodes.ZipperPattern_4152852_1.geometry} material={materials.Fabric4153031_FRONT_46401} />
      <mesh geometry={nodes.ZipperPattern_4152852_2.geometry} material={materials.Fabric4153031_SIDE_46401} />
      <mesh geometry={nodes.ZipperPattern_4152865.geometry} material={materials.Fabric4153031_FRONT_46401} />
      <mesh geometry={nodes.ZipperPattern_4152865_1.geometry} material={materials.Fabric4153031_FRONT_46401} />
      <mesh geometry={nodes.ZipperPattern_4152865_2.geometry} material={materials.Fabric4153031_SIDE_46401} />
      <mesh geometry={nodes.Internal_Line_4203094.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_4203094_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_4203094_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_4203095.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_4203095_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_4203095_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.ZipperPattern_4487929.geometry} material={materials.Fabric4488108_FRONT_46546} />
      <mesh geometry={nodes.ZipperPattern_4487929_1.geometry} material={materials.Fabric4488108_FRONT_46546} />
      <mesh geometry={nodes.ZipperPattern_4487929_2.geometry} material={materials.Fabric4488108_SIDE_46546} />
      <mesh geometry={nodes.ZipperPattern_4487942.geometry} material={materials.Fabric4488108_FRONT_46546} />
      <mesh geometry={nodes.ZipperPattern_4487942_1.geometry} material={materials.Fabric4488108_FRONT_46546} />
      <mesh geometry={nodes.ZipperPattern_4487942_2.geometry} material={materials.Fabric4488108_SIDE_46546} />
      <mesh geometry={nodes.Body_Back_1.geometry} material={materials.Body_FRONT_32299} />
      <mesh geometry={nodes.Body_Back_1_1.geometry} material={materials.Body_FRONT_32299} />
      <mesh geometry={nodes.Body_Back_1_2.geometry} material={materials.Body_FRONT_32299} />
      <mesh geometry={nodes.Body_Back_3.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Body_Back_3_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Body_Back_3_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Body_Back_4.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Body_Back_4_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Body_Back_4_2.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.ZipperPattern_4686608.geometry} material={materials.Fabric4686787_FRONT_46693} />
      <mesh geometry={nodes.ZipperPattern_4686608_1.geometry} material={materials.Fabric4686787_FRONT_46693} />
      <mesh geometry={nodes.ZipperPattern_4686608_2.geometry} material={materials.Fabric4686787_SIDE_46693} />
      <mesh geometry={nodes.ZipperPattern_4686621.geometry} material={materials.Fabric4686787_FRONT_46693} />
      <mesh geometry={nodes.ZipperPattern_4686621_1.geometry} material={materials.Fabric4686787_FRONT_46693} />
      <mesh geometry={nodes.ZipperPattern_4686621_2.geometry} material={materials.Fabric4686787_SIDE_46693} />
      <mesh geometry={nodes.Internal_Line_4946712.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_4946712_1.geometry} material={materials.metall_FRONT_32326} />
      <mesh geometry={nodes.Internal_Line_4946712_2.geometry} material={materials.metall_FRONT_32326} />
    </group>
  )
}

useGLTF.preload('/swaetshirt_men_gltf_orange.gltf')
